---
title: 'Analyses'
author: 
output: 
  github_document:
always_allow_html: true
editor_options: 
  chunk_output_type: console
---

```{r "setup", include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.align = "center",
                      fig.path=('../../report/figures/'))
library(rmarkdown)
```

# Required Packages &amp; Reproducibility
```{r "env", message=FALSE, warning=F}
rm(list=ls())
source(here::here("src/lib/functions.R"))
```

# Analyses
```{r "data for analyses"}
load(here::here("data/intermediate/cleaned_data_joined.RData"))
```

## Balance Checks

The figure below shows that the data is not unbalanced for any of the variables: As described in the Pre-Analysis Plan (p.10), we will not add any covariates to the analyses as controls.

```{r "balance-checks", fig.height=12, fig.width=8}
source(here("src/analysis/balance-test.R"))
df
```

## Baseline Model
```{r "baseline", fig.align="center", fig.height=4, fig.width=8}
source(here("src/analysis/baseline.R"))
b
rm(b_b, b1, b2, df, df_nl, df_us, tmp)
```

```{r "issues", fig.align="center", fig.height=16, fig.width=8}
source(here("src/analysis/issue_specific.R"))
b_i
rm(b1, b2, df, df_nl, df_us, tmp, issues_nl, issues_us, i)
```

## Ideological Bias hypothesis
```{r "h1", fig.align="center", fig.height=8, fig.width=8}
source(here("src/analysis/h1.R"))
p1a
p1b

(p1b_1+p1b_2)/(p1b_3 + p1b_4) + 
  plot_layout(guides = "collect") & theme(legend.position = 'bottom')
rm(df, df_nl, df_us, h1a, h1b, p1b_1, 
   pred1b_1, pred1b_2, pred1b_3, pred1b_4, tmp)
```

## Overinterpretation Hypotheses
```{r "h2", fig.align="center", fig.height=8, fig.width=8}
source(here("src/analysis/h2.R"))
p2a
p2b
p2c1
p2c2

(p2a_1+p2a_2)/(p2a_3 + p2a_4) + 
  plot_layout(guides = "collect") & theme(legend.position = 'bottom')

(p2b_1+p2b_2)/(p2b_3 + p2b_4) + 
  plot_layout(guides = "collect") & theme(legend.position = 'bottom')
rm(df, df_nl, df_us, h2a, h2a_2, h2b, h2b_2, tmp, tmpp,
   pred2a_1, pred2a_2, pred2a_3, pred2a_4, 
   pred2b_1, pred2b_2, pred2b_3, pred2b_4)
```

## Masking Hypothesis
```{r "h3", fig.align="center", fig.height=8, fig.width=8}
source(here("src/analysis/h3.R"))
p3a
p3b
p3c1
p3c2

(p3a_1+p3a_2)/(p3a_3 + p3a_4) + 
  plot_layout(guides = "collect") & theme(legend.position = 'bottom')

(p3b_1+p3b_2)/(p3b_3 + p3b_4) + 
  plot_layout(guides = "collect") & theme(legend.position = 'bottom')
rm(df, df_nl, df_us, h3a, h3a_2, h3b, 
   h3b_2,h3b_bs, h3b_2bs, tmp, tmpp,
   pred3a_1, pred3a_2, pred3a_3, pred3a_4, 
   pred3b_1, pred3b_2, pred3b_3, pred3b_4)
```

## Exploration
```{r "exploration", fig.height=7, fig.width=8}
source(here("src/analysis/exploration.R"))
p_b1
p_b2
p_e1a
p_e1b
p_e1c
```

```{r "explore-profiles", fig.height=10, fig.width=15}
source(here("src/analysis/profiles.R"))
prof1 
prof2
```

```{r "explor2", eval=FALSE, echo=FALSE}
source(here("src/analysis/profile_resp.R"))
kbl(e1_nlp, booktabs =T, caption = "\\label{tab:conditions}Profile Dutch Stance Annotators") %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F, fixed_thead = T, position = "center") %>%
  column_spec(1, width = "7cm") %>%
  column_spec(2, width = "7cm")

kbl(e1_ss, booktabs =T, caption = "\\label{tab:conditions2}Profile Dutch Stance Annotators") %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F, fixed_thead = T, position = "center") %>%
  column_spec(1, width = "7cm") %>%
  column_spec(2, width = "7cm")


kbl(e1_us_nlp, booktabs =T, caption = "\\label{tab:conditions_us}Profile American Stance Annotators") %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F, fixed_thead = T, position = "center") %>%
  column_spec(1, width = "7cm") %>%
  column_spec(2, width = "7cm")

kbl(e1_us_ss, booktabs =T, caption = "\\label{tab:conditions_us2}Profile American Stance Annotators") %>%
  kable_styling(latex_options = c("striped", "hold_position"),
                full_width = F, fixed_thead = T, position = "center") %>%
  column_spec(1, width = "7cm") %>%
  column_spec(2, width = "7cm")
```
